### ISSUE TITLE
Rogue AP Issue

### ISSUE THREAD

**Issue by AadiBiyani** [vanhoefm/ssid-confusion-hostap#3]
Every time I am running the attack it works and runs fine, but the log keeps saying did not receive beacon from host AP. Is there a way to fix this?

**Comment by vanhoefm** [comment]
Please mention the steps you took and the commands you executed, the output you got, and mention the results/output you expected instead. In this case it sounds like you might not have disabled the built-in network manager of the operating systems, which will interfere with the attack/scripts.
